### ISSUE TITLE
Create Item Group with all modded content.

### ISSUE THREAD

**Issue by Patbox** [borisshoes/ArcanaNovum#3]
Currently, this mod doesn't have Item Group setup, making it bit harder to see all the content added by it. Item groups added via polymer's api will be visible for players in creative either via `/polymer creative` command or installing polymer on client. It also will allow visibility of items in mods like Polydex (server side recipe viewer) or EMI. 

Direct support for Polydex could be also a good idea, but wouldn't say it's a requirement.

**Comment by borisshoes** [comment]
Thanks for the suggestion! I have had JEI/EMI compatibility on my planned feature list for a little bit, but haven't heard of Polydex before. I will add setting up an Item Group to the next patch.

**Comment by borisshoes** [comment]
Item Groups now added in v3.0.2
