### ISSUE TITLE
Request. Can you please make current version 1.21 compat?

### ISSUE THREAD

**Issue by Wytchcat** [borisshoes/ArcanaNovum#4]
Hey there,

We are one of a number of servers still using 1.21 and love the mod but would like to see the current release version avail for our server as well.

I'm receiving feedback from players that achievements in our Beta version are pretty vague but that overall they are loving the mod.

Any hope you might help us out?

We really appreciate it!

Wytch's Lair Admin

**Comment by borisshoes** [comment]
I'm so glad your players are enjoying Arcana! I will be releasing 3.0.2 in the next two or so days, and I will make sure it is 1.21 compatible.

Are your players referring to the achievements needed for researching items, or the achievements for using Arcana items? Most of the vaguer research achievements reference a vanilla achievement that they need to get, like eating every food, hitting a target block in the center, or falling from world height to bedrock.

**Comment by borisshoes** [comment]
v3.0.2 should be compatible with both 1.21 and 1.21.1 servers

**Comment by Wytchcat** [comment]
Thanks!

Updating now, will relate any feedback!

Wytchy
