### ISSUE TITLE
[Suggestion/Bug] Quiver Item Change

### ISSUE THREAD

**Issue by Daniel99j2** [borisshoes/ArcanaNovum#5]
Bug: When having a shield in the offhand, the bow does not show as 'loading' on the client, if you are using a quiver.
Suggestion: This could be fixed by having the quiver on the client side be a rabbit hide (as is currently) if there are no arrows, but if there are, then make it an arrow on the client side.

**Comment by borisshoes** [comment]
Thanks for the report! I will have it fixed in version 3.0.4. A temporary workaround is to have an arrow in your inventory along with the quiver.

**Comment by borisshoes** [comment]
Fixed this bug sooner than expected since I had to do an emergency patch. The fix only works if you have the mod's resource pack enabled through Polymer's config in your server config settings.
