### ISSUE TITLE
Issue with world creation task. Compat with Quantum

### ISSUE THREAD

**Issue by suerion** [borisshoes/ArcanaNovum#7]
Quantum is an Multiworld Mod https://modrinth.com/mod/quantum
had added there also an issue https://github.com/raevendev/Quantum/issues/3

Latest.log
https://mclo.gs/cqAAqTV

Crash File:
https://mclo.gs/fTapMz5

If you ned more informations, i can test it, because it is an DEV Enviroment on my side.

**Comment by borisshoes** [comment]
I put a fix in the upcoming patch, it'll be out in a few days. Let me know if it works for you.

**Comment by borisshoes** [comment]
Version 3.0.5 should fix this issue. If it is still giving an error, please upload an updated crash report!

**Comment by suerion** [comment]
I could here say, that this is fixed. ;) if there is another issue, i will come here again.

Thanks for your work

**Comment by borisshoes** [comment]
Glad to hear it! Enjoy the mod!
